# Generated by Django 3.1.3 on 2020-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201121_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='snippet',
            name='code',
            field=models.TextField(default='abcd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='abcd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
